"""Numeric

Revision ID: 5d8d48f2c1ed
Revises: a8072dfd57a1
Create Date: 2020-06-15 10:53:09.120382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d8d48f2c1ed'
down_revision = 'a8072dfd57a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('height', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'height')
    # ### end Alembic commands ###
